#!/bin/bash
#
# To enable this hook, rename this file to "pre-commit".

hook="./pre-commit"

echo -n "Making sure pre-commit is up-to-date..."
diff -q "${hook}" ./.git/hooks/pre-commit >> /dev/null
if [[ "$?" != "0" ]]; then
    echo; echo "  Files don't match; updating hook. Please re-run commit."
    cp "${hook}" ./.git/hooks/pre-commit
    exit 1
fi
echo "✅"


echo -n "Runing ruff..."
ruff -q check
if [[ "$?" != "0" ]]; then
    exit 1
fi
echo "✅"
