#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

echo -n "Making sure pre-commit is up-to-date..."
diff -q ./pre-commit ./.git/hooks/pre-commit >> /dev/null
if [[ "$?" != "0" ]]; then
    echo; echo "  Files don't match; updating hook. Please re-run commit."
    cp ./pre-commit ./.git/hooks/pre-commit
    exit 1
fi
echo "✅"


echo -n "Runing ruff..."
ruff -q check
if [[ "$?" != "0" ]]; then
    exit 1
fi
echo "✅"
